@bot.message_handler(func=lambda message: message.text =="Wayanad")
def  wayanad_button_selected(message):
  nest_nested_keyboard =ReplyKeyboardMarkup(resize_keyboard=True)
  travel_brochure1_button=KeyboardButton("travel brochure")
  park_button=KeyboardButton("park")
  beach_button=KeyboardButton("beach")
  dam_button=KeyboardButton("dam")
  wildlife_sanctuary_button=KeyboardButton("wildlife_sanctuary")
  Mountain_button=KeyboardButton("Montain")
  hills_button=KeyboardButton("Hills")
  Historical_place_button=KeyboardButton("Historical place")
  jungle_button=KeyboardButton("jungle")
  others_button=KeyboardButton("other")
  back_button = KeyboardButton("Back")
  main_menu_button = KeyboardButton("Main Menu")

  nest_nested_keyboard.row(travel_brochure1_button)
  nest_nested_keyboard.row(park_button)
  nest_nested_keyboard.row(beach_button)
  nest_nested_keyboard.row(dam_button)
  nest_nested_keyboard.row(wildlife_sanctuary_button)
  nest_nested_keyboard.row(Mountain_button)
  nest_nested_keyboard.row(hills_button)
  nest_nested_keyboard.row(Historical_place_button)
  nest_nested_keyboard.row(jungle_button)
  nest_nested_keyboard.row(others_button)
  nest_nested_keyboard.row(back_button)
  nest_nested_keyboard.row(main_menu_button)
 #Respond with a message when the user selects "" and include the nested keyboard
  bot.send_message(message.chat.id, 'Welcome to waynad ! What would you like to explore?', reply_markup=nest_nested_keyboard)
  user_states[message.chat.id] = "Wayanad_selected"